### ISSUE TITLE
L4D2_Internals error

### ISSUE THREAD

**Issue by seattleice** [ConfoglTeam/l4d2_direct#4]
There is a missing semi-colon on line 136 of L4D2_internals.inc

**Comment by ProdigySim** [comment]
This include doesn't actually use #pragma semicolon 1, so it should be fine, but I've fixed it for sameness-sake.

Should be fixed in d9c7b90204

**Comment by seattleice** [comment]
Good deal. Appreciate the code.

-----Original Message-----
