### ISSUE TITLE
L4D2_Direct.inc Issue

### ISSUE THREAD

**Issue by seattleice** [ConfoglTeam/l4d2_direct#5]
I get a compiler warning that L4D2_Direct_SetTankTickets should return a value. I know it is no biggie, but maybe just return the ticket number on success?

**Comment by ProdigySim** [comment]
Made to return nothing in all cases, like other setter functions. Fixed in 992a0ea9cb

**Comment by seattleice** [comment]
Cool, I like consistency as well.

-----Original Message-----
